export const GET_AUTH = 'GET_AUTH';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_FAILED = 'AUTH_FAILED';

export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const PARTICIPANTS_LOADING = 'PARTICIPANTS_LOADING';
export const PARTICIPANTS_FAILED = 'PARTICIPANTS_FAILED';

export const GET_GROUPS = 'GET_GROUPS';
export const GROUPS_LOADING = 'GROUPS_LOADING';
export const GROUPS_FAILED = 'GROUPS_FAILED';