export const GET_AUTH = 'GET_AUTH';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_FAILED = 'AUTH_FAILED';

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING"
export const PROFILE_FAILED = "PROFILE_FAILED";

export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';
export const PARTICIPANTS_LOADING = 'PARTICIPANTS_LOADING';
export const PARTICIPANTS_FAILED = 'PARTICIPANTS_FAILED';

export const GET_GROUPS = 'GET_GROUPS';
export const GROUPS_LOADING = 'GROUPS_LOADING';
export const GROUPS_FAILED = 'GROUPS_FAILED';

export const GET_QUIZES = 'GET_QUIZES';
export const QUIZES_LOADING = 'QUIZES_LOADING';
export const QUIZES_FAILED = 'QUIZES_FAILED';

export const GET_USERS = 'GET_USERS';
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FAILED = 'USERS_FAILED';

export const GET_RESULTS = "GET_RESULTS";
export const RESULTS_LOADING = "RESULTS_LOADING";
export const RESULTS_FAILED = "RESULTS_FAILED";
